name: Build and Pre-Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Setup Node.js & Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: '16'
          cache: npm

      - name: Build preview
        run: |
          npm install -g pkg
          npm install
          npm run build

      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: package.json
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            ./build/*
            package.json
            README.md
            LICENSE.md

  create-win-archive:
    name: Create windows archive
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download package artifact
        uses: actions/download-artifact@v2
        with:
          name: package

      - name: Download executables
        uses: actions/download-artifact@v2
        with:
          name: build
  
      - name: Extract project version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'package.json'
          prop_path: 'version'

      - name: Extract project name
        id: name
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'package.json'
          prop_path: 'name'

      - name: Create archive
        uses: montudor/action-zip@v1
        with:
          args: zip -j ${{ steps.name.outputs.prop }}-win-${{ steps.version.outputs.prop }}-preview.zip ./build/${{ steps.name.outputs.prop }}-win.exe LICENSE.md README.md

      - name: Upload archive
        uses: actions/upload-artifact@v2
        with:
          name: win-archive
          path: ${{ steps.name.outputs.prop }}-win-${{ steps.version.outputs.prop }}-preview.zip

  create-linux-archive:
    name: Create linux archive
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download package artifact
        uses: actions/download-artifact@v2
        with:
          name: package

      - name: Download executables
        uses: actions/download-artifact@v2
        with:
          name: build
  
      - name: Extract project version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'package.json'
          prop_path: 'version'

      - name: Extract project name
        id: name
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'package.json'
          prop_path: 'name'

      - name: Create archive
        uses: montudor/action-zip@v1
        with:
          args: zip -j ${{ steps.name.outputs.prop }}-linux-${{ steps.version.outputs.prop }}-preview.zip ./build/${{ steps.name.outputs.prop }}-linux LICENSE.md README.md

      - name: Upload archive
        uses: actions/upload-artifact@v2
        with:
          name: linux-archive
          path: ${{ steps.name.outputs.prop }}-linux-${{ steps.version.outputs.prop }}-preview.zip

  create-macos-archive:
    name: Create macOS archive
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download package artifact
        uses: actions/download-artifact@v2
        with:
          name: package

      - name: Download executables
        uses: actions/download-artifact@v2
        with:
          name: build
  
      - name: Extract project version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'package.json'
          prop_path: 'version'

      - name: Extract project name
        id: name
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'package.json'
          prop_path: 'name'

      - name: Create archive
        uses: montudor/action-zip@v1
        with:
          args: zip -j ${{ steps.name.outputs.prop }}-macos-${{ steps.version.outputs.prop }}-preview.zip ./build/${{ steps.name.outputs.prop }}-macos LICENSE.md README.md

      - name: Upload archive
        uses: actions/upload-artifact@v2
        with:
          name: macos-archive
          path: ${{ steps.name.outputs.prop }}-macos-${{ steps.version.outputs.prop }}-preview.zip

  upload-pre-release:
    name: Upload Pre-release
    runs-on: ubuntu-latest
    needs: [create-linux-archive, create-win-archive, create-macos-archive]

    steps:
      - name: Download package artifact
        uses: actions/download-artifact@v2
        with:
          name: package

      - name: Extract project version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'package.json'
          prop_path: 'version'

      - name: Extract project name
        id: name
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'package.json'
          prop_path: 'name'

      - name: Get windows archive
        uses: actions/download-artifact@v2
        with:
          name: win-archive
          path: ./archives/

      - name: Get linux archive
        uses: actions/download-artifact@v2
        with:
          name: linux-archive
          path: ./archives/

      - name: Get macOS archive
        uses: actions/download-artifact@v2
        with:
          name: macos-archive
          path: ./archives/
        
      - name: Upload Pre-release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ github.token }}
          automatic_release_tag: nightly
          prerelease: true
          title: ${{ steps.name.outputs.prop }} v${{ steps.version.outputs.prop }} preview
          files: ./archives/*
