name: Build and Pre-Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_matrix:
    name: Setup Node.js & Build
    strategy:
      matrix:
        os: [windows, macos, ubuntu]
        include:
          - os: windows
            build: npx caxa --input . --output build/ded_bot-win.exe -- "{{caxa}}/node_modules/.bin/node" "--experimental-json-modules" "{{caxa}}/bin/server.js"
          - os: macos
            build: npx caxa --input . --output build/ded_bot-macos -- "{{caxa}}/node_modules/.bin/node" "--experimental-json-modules" "{{caxa}}/bin/server.js"
          - os: ubuntu
            build: npx caxa --input . --output build/ded_bot-linux -- "{{caxa}}/node_modules/.bin/node" "--experimental-json-modules" "{{caxa}}/bin/server.js"
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - run: npm ci
      - run: ${{ matrix.build }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            ./build/*
            package.json
            README.md
            LICENSE.md

  create-archive:
    name: Create archives
    needs: [build_matrix]
    runs-on: ubuntu-latest

    steps:
      - name: Download executables
        uses: actions/download-artifact@v2
        with:
          name: build

      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: package.json
  
      - name: Extract project version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'package.json'
          prop_path: 'version'

      - name: Extract project name
        id: name
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'package.json'
          prop_path: 'name'

      - run: mkdir ./archives/

      - name: Create windows archive
        uses: montudor/action-zip@v1
        with:
          args: zip -j ./archives/${{ steps.name.outputs.prop }}-win-${{ steps.version.outputs.prop }}-preview.zip ./build/${{ steps.name.outputs.prop }}-win.exe LICENSE.md README.md

      - name: Create macos archive
        uses: montudor/action-zip@v1
        with:
          args: zip -j ./archives/${{ steps.name.outputs.prop }}-macos-${{ steps.version.outputs.prop }}-preview.zip ./build/${{ steps.name.outputs.prop }}-macos.exe LICENSE.md README.md

      - name: Create linux archive
        uses: montudor/action-zip@v1
        with:
          args: zip -j ./archives/${{ steps.name.outputs.prop }}-linux-${{ steps.version.outputs.prop }}-preview.zip ./build/${{ steps.name.outputs.prop }}-linux.exe LICENSE.md README.md

      - name: Upload archive
        uses: actions/upload-artifact@v2
        with:
          name: archive
          path: ./archives/*

  upload-pre-release:
    name: Upload Pre-release
    runs-on: ubuntu-latest
    needs: [create-archive]

    steps:
      - name: Download package artifact
        uses: actions/download-artifact@v2
        with:
          name: package

      - name: Get archive
        uses: actions/download-artifact@v2
        with:
          name: archive
          path: ./archives/

      - name: Extract project version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'package.json'
          prop_path: 'version'

      - name: Extract project name
        id: name
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'package.json'
          prop_path: 'name'

      - name: Upload Pre-release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ github.token }}
          automatic_release_tag: nightly-v${{ steps.version.outputs.prop }}
          prerelease: true
          title: ${{ steps.name.outputs.prop }} v${{ steps.version.outputs.prop }} preview
          files: ./archives/*
